//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFSCnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public string job_num { get; set; }
        public string name { get; set; }
        public bool sex { get; set; }
        public Nullable<int> dept { get; set; }
        public Nullable<int> role { get; set; }
        public string phone { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
