//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFSCnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gifts
    {
        public Gifts()
        {
            this.Records = new HashSet<Records>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public int mkt_price { get; set; }
        public string detail { get; set; }
        public int reserve { get; set; }
        public bool active { get; set; }
        public string imgUrl { get; set; }
    
        public virtual ICollection<Records> Records { get; set; }
    }
}
