//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFSCnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int Id { get; set; }
        public int buyer_id { get; set; }
        public int gift_id { get; set; }
        public int amount { get; set; }
        public int cost { get; set; }
        public System.DateTime createddt { get; set; }
        public bool active { get; set; }
    
        public virtual Gifts Gifts { get; set; }
        public virtual Users Users { get; set; }
    }
}
